### ISSUE TITLE
竞赛生史·戈骚传 | Welcome to MCJiu's Blog!

### ISSUE THREAD

**Issue by MCJiu** [MCJiu/mcjiu.github.io#1]
https://blog.mcjiu.ml/2020/07/13/%E7%AB%9E%E8%B5%9B%E7%94%9F%E5%8F%B2%C2%B7%E6%88%88%E9%AA%9A%E4%BC%A0/#%E9%AA%9A%E7%8E%8B%E5%8E%BB%E4%B8%96 

 竞赛生史系列 胡教授著

**Comment by MCJiu** [comment]
***mèi有人a?***

**Comment by IgnotusJee** [comment]
窝笑死啦
——波波

**Comment by GoPoux4** [comment]
> 我笑死啦
>
>—— 波尔
